bootcamp-students/s24-warmups

maddie-carlson/day-26/duplicates.js, maddie-carlson/day-26/mask.js, maddie-carlson/day-26/unique-number.js, maddie-carlson/day-27/pig-latin.js, maddie-carlson/day-27/surface-area-volume.py, maddie-carlson/day-27/tip-calculator.py, maddie-carlson/day-28/array-sum.py, maddie-carlson/day-28/shortest-word.py, maddie-carlson/day-29/basic-math.py, maddie-carlson/day-29/coin-combos.py
Maddie here is your week 6 feedback. Great work! You just need to rename some of the python files
=> Maddie week 6 feedback

ryan-anderson/day-36/breaking_chocolate_problem.py, ryan-anderson/day-36/concactenating_columns.sql, ryan-anderson/day-36/kill_the_monsters.py, ryan-anderson/day-37/keep_hydrated.py, ryan-anderson/day-37/make_the_deadfish_swim.py, ryan-anderson/day-38/unique_in_order.py, ryan-anderson/day-38/who_likes_it.py, ryan-anderson/day-39/create_phone_number.py
=> 279 week 8 feedback for ryan anderson

ryan-anderson/day-31/century-from-year.py, ryan-anderson/day-31/remove-string-spaces.py, ryan-anderson/day-32/easy-sql-ordering.sql, ryan-anderson/day-32/length-based-select-with-like.sql, ryan-anderson/day-33/ascii-converter.sql, ryan-anderson/day-33/basic-repeat-and-reverse.sql, ryan-anderson/day-33/best-selling-books.sql, ryan-anderson/day-33/find-all-active-students.sql, ryan-anderson/day-33/trimming-the-field.sql, ryan-anderson/day-34/absolute-value-and-log-to-base.sql, ryan-anderson/day-34/conitional-count.sql, ryan-anderson/day-34/simple-exists.sql, ryan-anderson/day-34/simple-group-by.sql
Here is your week 7 feedback! Go through and change file names to snake_case. Good work :)
=> Ryan week 7 feedback

henry-knollenberg/day-26/counting-duplicates.js, henry-knollenberg/day-26/credit-card-mask.js, henry-knollenberg/day-27/simple-pig-latin.js, henry-knollenberg/day-27/surface-area-and-volume-of-a-box.py, henry-knollenberg/day-27/tip.calculator.py, henry-knollenberg/day-28/array-plus-array.py, henry-knollenberg/day-28/shortest-word.py, henry-knollenberg/day-29/basic-math.py, henry-knollenberg/day-29/calculator-coin-combination.py
Henry, here is your feedback for week 6. You need to push up some changes, let me know if you have any questions. Thanks!
=> Henry week 6 feedback

henry-knollenberg/day-31/century-from-year.py, henry-knollenberg/day-31/remove-string-spaces.py, henry-knollenberg/day-32/length-based-select-with-like.sql, henry-knollenberg/day-32/ordering.sql, henry-knollenberg/day-33/ASCII-converter.sql, henry-knollenberg/day-33/best-selling-books.sql, henry-knollenberg/day-33/find-all-active-students.sql, henry-knollenberg/day-33/repeat-and-reverse.sql, henry-knollenberg/day-33/trimming-the-field.sql, henry-knollenberg/day-34/absolute-value-and-log-to-base.sql, henry-knollenberg/day-34/conditional-count.sql, henry-knollenberg/day-34/exists.sql, henry-knollenberg/day-34/group-by.sql
Henry here is your feedback for week 7! Great work :D Go through and rename your files but other than that you are good.
=> Henry week 7 feedback

duke-mcclellan/day-26/credit-card-mask.js, duke-mcclellan/day-26/find-unique-number.js, duke-mcclellan/day-27/simple-pig-latin.js, duke-mcclellan/day-27/surface-area.py, duke-mcclellan/day-27/tip-calculator.py, duke-mcclellan/day-28/array-plus-array.py, duke-mcclellan/day-28/shortest-word.py, duke-mcclellan/day-29/basic-math.py, duke-mcclellan/day-29/coin_combo.py
Duke here is your week 6 feedback. Need to rename some of the files to be properly snake_case which is the industry convention for python.
=> Duke week 6 feedback

henry-knollenberg/day-36/breaking_chocolate_problem.py, henry-knollenberg/day-36/concatenating_columns.sql, henry-knollenberg/day-36/kill_the_monsters.py, henry-knollenberg/day-37/keep_hydrated.py, henry-knollenberg/day-37/make_the_deadfish_swim.py, henry-knollenberg/day-38/unique_in_order.py, henry-knollenberg/day-38/who_likes_it.py, henry-knollenberg/day-39/create_phone_number.py
=> Henry week 8 feedback

cody-miller/day-31/century.py, cody-miller/day-31/no-spaces.py, cody-miller/day-32/SQL-ordering, cody-miller/day-32/length-like, cody-miller/day-33/all_students, cody-miller/day-33/convert_ascii, cody-miller/day-33/repeat_reverse, cody-miller/day-33/selling_books, cody-miller/day-33/trimming, cody-miller/day-34/abs_val.py, cody-miller/day-34/conditional_count.py, cody-miller/day-34/exists.py, cody-miller/day-34/group_by.py
Didn't give a lot of feedback, almost all of the files didn't have an extension or had an incorrect extension.
=> Cody week 7 feedback

maddie-carlson/day-31/century-from-year.py, maddie-carlson/day-31/remove_spaces.py, maddie-carlson/day-32/length-based-select.sql, maddie-carlson/day-32/sql-ordering.sql, maddie-carlson/day-33/active-students.sql, maddie-carlson/day-33/ascii-converter.sql, maddie-carlson/day-33/best-sellers.sql, maddie-carlson/day-33/repeat-and-reverse.sql, maddie-carlson/day-33/trimming-the-field.sql, maddie-carlson/day-34/abs-log.sql, maddie-carlson/day-34/age-count.sql, maddie-carlson/day-34/conditional-count.sql, maddie-carlson/day-34/simple-exists.sql
Great job! Go through and make all Python and SQL file names snakes case, other than that great job! I hope you learned a lot about SQL and the power of friendship. :)
=> Maddie week 7 feedback

jacinta-helm/day-27/surface-area-volume.py, jacinta-helm/day-28/array_plus_array.py, jacinta-helm/day-28/shortest_word.py, jacinta-helm/day-29/basic_math.py, jacinta-helm/day-29/coin_combo.py
Here is your feedback for week 6! Finished the week strong, really good job on the back half. You do need to circle back and get days 26 and 27 submitted or altered. Good work though! Because main is locked down you will need to make a new branch to hold all the requested changes from this week. You can make a pull request on main then dm me on slack so I can review it.
=> Jacinta week 6 feedback

caitlin-schaeffer/day-36/breaking_chocolate.py, caitlin-schaeffer/day-36/concatenating_columns.sql, caitlin-schaeffer/day-36/kill_monsters.py, caitlin-schaeffer/day-37/keep_hydrated.py, caitlin-schaeffer/day-37/make_deadfish_swim.py, caitlin-schaeffer/day-38/unique_in_order.py, caitlin-schaeffer/day-38/who_likes_it.py, caitlin-schaeffer/day-39/create_phone_numbers.py
Week 8 Kata Warmup Submissions
=> Caitlin schaeffer week 8 submissions

neal-sharma/day-31/century.py, neal-sharma/day-31/remove_spaces.py, neal-sharma/day-32/first_name.sql, neal-sharma/day-32/ordering.sql, neal-sharma/day-33/books.sql, neal-sharma/day-33/converter.sql, neal-sharma/day-33/repeat_reverse.sql, neal-sharma/day-33/students.sql, neal-sharma/day-33/trim_field.sql, neal-sharma/day-34/cond_count.sql, neal-sharma/day-34/exists.sql, neal-sharma/day-34/group_by.sql, neal-sharma/day-34/value_base.sql
Great job!! Nailed it 😄 best one so far
=> Neal week 7 feedback

jay-miller/Day-31/Century-From-Year.py, jay-miller/Day-31/Remove-String-Spaces.py, jay-miller/Day-32/BASICS-Length-based-SELECT-with-LIKE.sql, jay-miller/Day-32/Easy-SQL.sql, jay-miller/Day-33/Best-Selling-Books.sql, jay-miller/Day-33/EASY-SQL-ASCII.sql, jay-miller/Day-33/Find-all-active-students.sql, jay-miller/Day-33/SQL-BASICS-repeat-reverse.sql, jay-miller/Day-33/Trimming-the-field.sql, jay-miller/Day-34/Absolute-value-and-Log-to-base.sql, jay-miller/Day-34/Conditional-Count.sql, jay-miller/Day-34/Simple-Exists.sql, jay-miller/Day-34/Simple-GROUP-BY.sql
Jay here is your week 7 feedback. Good job this week! You need to update all the file names and your century problem was iffy but otherwise good job.
=> Jay week 7 feedback

jay-miller/Day-26/Credit-Card-mask.js, jay-miller/Day-27/Simple-Pig-Latin.js, jay-miller/Day-27/Surface-Area-Of-Box.py, jay-miller/Day-27/Tip-Calculator.py, jay-miller/Day-28/Array-Plus-Array.py, jay-miller/Day-28/shortest-word.py, jay-miller/Day-29/Basic-Math-AddorSubtract.py, jay-miller/Day-29/coin-combination.py
Here is your week 6 feedback. Need to rename some files. Missing one of the katas from day 26.
=> Jay week 6 feedback

nathan-wilson/day-31/century_from_year.py, nathan-wilson/day-31/remove_string_spaces.py, nathan-wilson/day-32/length_based_select_with_like.sql, nathan-wilson/day-32/ordering.sql, nathan-wilson/day-33/ascii_converter.sql, nathan-wilson/day-33/best_selling_books.sql, nathan-wilson/day-33/find_all_active_students.sql, nathan-wilson/day-33/repeat_and_reverse.sql, nathan-wilson/day-33/trimming_the_field.sql, nathan-wilson/day-34/absolute_value_and_log_base.sql, nathan-wilson/day-34/conditional_count.sql, nathan-wilson/day-34/simple_exists.sql, nathan-wilson/day-34/simple_group_by.sql
Here is your week 7 feedback! Everything looked great! :D
=> Nathan Week 7 feedback

ryan-anderson/day-41/buying-a-car.js, ryan-anderson/day-41/convert_string_to_camel_case.py, ryan-anderson/day-42/maximum-subarray-sum.js, ryan-anderson/day-42/sliding_puzzle_verification.py, ryan-anderson/day-43/are_they_the_same.py, ryan-anderson/day-44/scramblies.js
My code formatter doesn't like it when you put comments at the end of the line. I tried to clean it up by hand a little but I wasn't going to do that for all of them. Here is your week 9 feedback. Good job!
=> Ryan week 9 feedback

brandon-heisler/day-36/breaking_chocolate.py, brandon-heisler/day-36/concatenating_columns.sql, brandon-heisler/day-36/kill_the_monsters.py, brandon-heisler/day-37/keep_hydrated.py, brandon-heisler/day-37/make_deadfish_swim.py, brandon-heisler/day-38/unique_in_order.py, brandon-heisler/day-38/who_likes_it.py, brandon-heisler/day-39/create_phone_number.py
Brandon, great work! Here is my feedback on your solutions. They were really great! You basically solved everything in more or less the ideal manor, so I didn't have much to say. On a few I showed alternative ways to solve the problem, using different syntax so you can get used to reading code that looks different but does the same thing.
=> Brandon week 8 feedback

maddie-carlson/day-36/breaking_chocolate.py, maddie-carlson/day-36/concat-columns.sql, maddie-carlson/day-36/kill_the_monsters.py, maddie-carlson/day-37/deadfish.py, maddie-carlson/day-37/keep_hydrated.py, maddie-carlson/day-38/unique_in_order.py, maddie-carlson/day-38/who_likes_it.py, maddie-carlson/day-39/phone_number.py
Maddie, great work! Wonderful solutions and pseudocode as always 😄
=> Maddie week 8 feedback

caitlin-schaeffer/day-41/buying-a-car.js, caitlin-schaeffer/day-41/convert_to_camel.py, caitlin-schaeffer/day-42/max-subarray-sum.js, caitlin-schaeffer/day-42/sliding_puzzle_verification.py, caitlin-schaeffer/day-43/are_they_the_same.py, caitlin-schaeffer/day-44/scramblies.js
Hey Caitlin, good work! Lets work on the sliding puzzle and scramblies katas together to get them working.
=> Caitlin week 9 feedback

jacinta-helm/day-41/buying-a-car.js, jacinta-helm/day-41/to_camel_case.py, jacinta-helm/day-42/max_sum_array.js, jacinta-helm/day-42/sliding_puzzle.py, jacinta-helm/day-43/are_they_the_same.py, jacinta-helm/day-44/scramblies.js
Here is your week 9 feedback, good work
=> Week 9 feedback Jacinta
